# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Harry Pantazis
tagline:          ''
description:      'Junior Software Developer | GSoCer'
baseurl:          

author:
  name:           'Harry Pantazis'
  url:            'luserx0.github.io'
  email:          'luserx0@gmail.com'
  github:         'https://github.com/luserx0'
  linkedin:       ''


paginate:         3

# Custom vars
github:
  repo:           https://github.com/luserx0

gems: [jekyll-gist, jekyll-paginate]
