# Dependencies
highlighter:      black

# Permalinks
permalink:        pretty

# Setup
title:            Harry Pantazis
description:      'Open Source Software Engineer'
baseurl:

author:
  name:           'Harry Pantazis'
  url:            'luserx0.me'
  email:          'luserx0@gmail.com'
  github:         'https://github.com/luserx0'


paginate:         1

# Custom vars
github:
  repo:           https://github.com/luserx0

gems: [jekyll-gist, jekyll-paginate]
